[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json ={version="1.0.93"}
gtk = { version = "0.6.0", package = "gtk4", features = ["v4_8"] }